### ISSUE TITLE
GitHub Action - `if: ! ... [skip ci]` not needed anymore

### ISSUE THREAD

**Issue by MrChocolatine** [NullVoxPopuli/ember-statechart-component#146]
From your workflows:
https://github.com/NullVoxPopuli/ember-statechart-component/tree/v2.3.7/.github/workflows

As GitHub Action natively supports `[skip ci]` and similar:
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Comment by NullVoxPopuli** [comment]
Yaaaaas. Thank you for letting me know!

**Comment by MrChocolatine** [comment]
It's about time! ;-)

**Comment by NullVoxPopuli** [comment]
Removed, thank you!
