### ISSUE TITLE
README should be specific

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-statechart-component#188]
The paragraph:

> XState provides its own [`matches`](https://xstate.js.org/api/classes/state.html#matches)
> method which is available on the `state` object.
> We can utilize this provided there exists a `HelperManager` for
> handling vanilla functions, such as what
> [ember-could-get-used-to-this](https://github.com/pzuraq/ember-could-get-used-to-this)
provides.

Left me wondering what am I supposed to do? Install that addon? Install & configure something somewhere? What is `HelperManger` anyway? Why should I care?

Proposal:
- Tell user what to do with a good default option
- Explain in the notes why was this necessary

**Comment by NullVoxPopuli** [comment]
I think you PR'd this?

**Comment by MichalBryxi** [comment]
My OSS skills be rusty. Solved in #189.
