### ISSUE TITLE
How can I use `@context`?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-statechart-component#191]
- [x] The API section says that `@context` exists. It's obvious to some Ember users that you mean `<Toggle @context=...`, but not to all an example how to pass in context would be good
- [x] Can I then grab the mutated `@context` data back in my template? How?

**Comment by NullVoxPopuli** [comment]
I think you PR'd both of these? (and they're now merged?)

**Comment by MichalBryxi** [comment]
Fixed in #192
