### ISSUE TITLE
Contradiction?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-statechart-component#193]
These two sentences:

> ... Any changes to this argument are ignored.

And:

> What happens if any of the passed args change? An event will be sent to the machine for you...

Seem to contradict each other.

**Comment by MichalBryxi** [comment]
I don't know what is the current or expected behaviour there. Can't decide on how to improve the documentation.

**Comment by NullVoxPopuli** [comment]
maybe the second part should say 
"for example, changes to `@state` cause the `ARGS_UPDATE` event to be sent to your machine, but it's up to you to decide what to do, if anything with the new `@state` value"

? :shrug:

**Comment by MichalBryxi** [comment]
Ok, so if I change `@state` on the fly, it's ignored and nothing changes on the machine. The lack of this sentence at `@context` and `@config` suggests that for those two the changes will be propagated?

If that's the case, I'd say something like:

> @state
> The machine will use `@state` as the initial state. Any changes to this argument are not automatically propagated to the machine. An `ARGS_UPDATE ` event (see details below) is sent instead.

Might make it clearer? I'm just trying to get rid of that definitive "changes are ignored", which might sound like it won't even be part of the `ARGS_UPDATE`.

**Comment by NullVoxPopuli** [comment]
Yeah, that reads well
