### ISSUE TITLE
Is @config really MachineConfig?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-statechart-component#268]
The README says:

> #### `@config`
> This argument allows you to pass a MachineConfig for actions, services, guards, etc...

When I look up `MachineConfig` in the xstate docs I will get to: https://xstate.js.org/docs/packages/xstate-fsm/#machine-config which is defined as:

```
- id (string) - an identifier for the type of machine this is. Useful for debugging.
- initial (string) - the key of the initial state.
- [states](https://xstate.js.org/docs/packages/xstate-fsm/#state-config) (object) - an object mapping state names (keys) to states
[#](https://xstate.js.org/docs/packages/xstate-fsm/#state-config)
```

Which does not have `actions` key as shown in the `@config` examples:

```
<Toggle 
  @config={{hash 
    actions=(hash 
      toggleIsOn=@onRoomIlluminated
    )
  }} 
```

So I _think_ what `@config` is actually referring to is [MachineOptions](https://xstate.js.org/docs/packages/xstate-fsm/#machine-options). Guessing based on [createMachine](https://xstate.js.org/docs/packages/xstate-fsm/#createmachine-config-options) syntax and knowledge how this fits together. So the docs wording should be changed:

```
#### `@config`
This argument allows you to pass a [MachineOptions](https://xstate.js.org/docs/packages/xstate-fsm/#machine-options) for ...
```

**Comment by MichalBryxi** [comment]
*If* I'm correct, then the name of the argument `@config` is not fortunate as it does not map 1to1 to xstate terminology. If I'm wrong, then the docs could use some better hints.

**Comment by MichalBryxi** [comment]
Kidna relates to #267

**Comment by MichalBryxi** [comment]
Also note that I created a bug ticket to enhance xstate docs to make it more explicit on their side: https://github.com/statelyai/xstate/issues/3165

**Comment by NullVoxPopuli** [comment]
I'd be happy to accept a PR changing the docs to say `MachineOptions` -- maybe also with the type https://paka.dev/npm/xstate@4.32.1/api#181eea99810c28a0 since the main docs are presently incomplete?
