### ISSUE TITLE
More-native Glint integration?

### ISSUE THREAD

**Issue by dfreeman** [NullVoxPopuli/ember-statechart-component#416]
I don't have a deep enough understanding of how XState's types work to provide _super_ precise input here, but based on a shallow reading it seems like it should be possible to avoid needing the `asComponent` function here, instead doing something like this in `src/glint.ts`:

```ts
declare module 'xstate' {
  export interface StateMachine<...> /* or maybe `StateNode`? */ 
    extends ComponentLike<{
      // derived from the zillion type params on `StateMachine`
    }> {}
}

// Maintain as just the identity function for backwards compatibility
export function asComponent<T extends AnyStateMachine>(machine: T): T {
  return machine;
}
```

Then downstream consumers would only need to `import 'ember-statechart-component/glint'` to "activate" the Glint integration and their other code could stay as-is.

**Comment by NullVoxPopuli** [comment]
yeah! -- it would be ideal if there wasn't a an `asComponent` function to use. I had a go at re-defining `StateMachine` -- but it was getting hairy -- I then looked at the implementation: https://github.com/statelyai/xstate/blob/780458c921d4525c7a00119c7eb43d4833978861/packages/core/src/types.ts#L1027 -- and I'm not sure if it makes sense to re-define all that from a maintenance perspective.

And I know XState v5 is around the corner -- not sure what changes are coming there -- but maybe this'll be a good thing to explore in v5?

**Comment by dfreeman** [comment]
You shouldn't need to redefine anything—the interface you define there will be merged with the one from xstate itself.

**Comment by NullVoxPopuli** [comment]
ah ok, well, I think this does it: https://github.com/NullVoxPopuli/ember-statechart-component/pull/417

:partying_face: 

Thank you!!
