### ISSUE TITLE
yield out a helper to register a transition callback/handler

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/ember-statechart-component#43]
```hbs
<Machine as |state send onTransition|>
  {{onTransition this.doSomething}}
</Machine>
```

**Comment by nightire** [comment]
I'm thinking how to implement this, not sure what's your initial motive to use a helper.

I have another simple plan is to allow passing a handler as an argument:

```hbs
<Machine @onTransition={{this.doSomething}} as |state send|>
  ...
</Machine>
```

then `reactiveInterpreter` takes two arguments:

```ts
reactiveInterpreter(interpreter, named.onTransition);
```

and call the handler in the `onTransition` hook:

```ts
interpreter.onTransition(async (state: State<unknown>, event: EventObject) => {
  // ...
  dirtyState(interpreter);

  if (typeof onTransition === 'function') {
    onTransition(state, event);
  }
});
```

thoughts?

**Comment by NullVoxPopuli** [comment]
what if you want multiple things to happen `onTransition`?

**Comment by NullVoxPopuli** [comment]
> not sure what's your initial motive to use a helper.

to yield out `this.onTransition`, iirc

**Comment by nightire** [comment]
> what if you want multiple things to happen `onTransition`?

you can do anything in the passing callback, nothing prevents you want to do multiple things, right?

**Comment by NullVoxPopuli** [comment]
sure, but in a template-only context, you can't compose functions

**Comment by nightire** [comment]
> sure, but in a template-only context, you can't compose functions

You mean like this?

```hbs
<Machine as |state send onTransition|>
  {{onTransition @doOneThing}}
  ...
  {{onTransition @doAnotherThing}}
</Machine>
```

**Comment by NullVoxPopuli** [comment]
yup

**Comment by NullVoxPopuli** [comment]
This has been implemented since January 20, 2022 -- gonna close -- feel free to open a new issue if there are questions.
