### ISSUE TITLE
How to use arguments?

### ISSUE THREAD

**Issue by phcoliveira** [NullVoxPopuli/ember-statechart-component#461]
Hello there!

Would it be possible to use arguments with a statechart component?

If yes, then how?

**Comment by NullVoxPopuli** [comment]
yes! it is possible -- I think you want to use `@context` https://github.com/NullVoxPopuli/ember-statechart-component#api

and then be sure to handle the `ARGS_UPDATE` event on the machine for when the args change

**Comment by phcoliveira** [comment]
I am sorry, I should have been more specific.
I was already aware of the arguments `@config` and `@context`.
What I meant what to use regular arguments to be accessed by `this.args`.
I guess it is not possible, so a combination of some data passed to `@context` and some functions to `@config` is needed.
@NullVoxPopuli

**Comment by NullVoxPopuli** [comment]
Yeah, inside the statechart, there aren't really any ember-specific additions. All dana is managed on the context, so that following the xstate docs works 1 to 1
