### ISSUE TITLE
xstate version?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-statechart-component#489]
Current [package.lock](https://github.com/NullVoxPopuli/ember-statechart-component/blob/df412522c1bf26cd327e84f35ba645fef9e1ca0f/ember-statechart-component/package.json#L59) `peerDependencies` says:

```
    "xstate": "^4.32.1"
```

but the [README](https://github.com/NullVoxPopuli/ember-statechart-component/blob/main/README.md?plain=1#L13) says:

```
- XState >= 5
```

Isn't this a contradiction?

**Comment by MichalBryxi** [comment]
Coming here beacuse in a new app with `"ember-statechart-component": "^6.1.2",` I got:

```
 WARN  Issues with peer dependencies found
.
└─┬ ember-statechart-component 6.1.2
  └── ✕ unmet peer xstate@^4.32.1: found 5.10.0
```

**Comment by MichalBryxi** [comment]
To rendom bypassers: When I had `xstate: 5.10.0` I was getting:

```
Uncaught Error: Attempted to load a component, but there wasn't a component manager associated with the definition. The definition was: StateMachine
```

Whenever I downgraded to recommended `xstate: 4.32.1` the problem has disappeared and xstate started working for me.

**Comment by NullVoxPopuli** [comment]
Yeah, i'm mid-rewrite of this library to support xstate5, but i forgot to finish!

Xstate5 has a ton of breaking changes

**Comment by NullVoxPopuli** [comment]
latest version now supports for xstate 5!
